on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Run tests

jobs:
    test:
      name: Run unittests and examples
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
          dc: [dmd-latest, ldc-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - name: Install D compiler
          uses: dlang-community/setup-dlang@v1
          with:
            compiler: ${{ matrix.dc }}
        - name: Run tests
          run: dub test
          env:
            CI: true
